SRC_LIB		=	array/array_to_generic_list.c			\
				array/array_to_ptr_list.c				\
				array/array_to_string_list.c			\
				array/free_2d_array.c					\
				array/generic_list_to_array.c			\
				array/ptr_list_to_array.c				\
				array/string_list_to_array.c			\
				container/container_add_node.c			\
				container/container_clear.c				\
				container/container_delete_node.c		\
				container/container_get_node.c			\
				container/container_merge.c				\
				container/container_remove_node.c		\
				container/container_reverse.c			\
				container/container_rotate.c			\
				container/create_node.c					\
				container/destroy_node.c				\
				generic_list/generic_list_clear.c		\
				generic_list/generic_list_create.c		\
				generic_list/generic_list_destroy.c		\
				generic_list/generic_list_dup.c			\
				generic_list/generic_list_emplace.c		\
				generic_list/generic_list_find.c		\
				generic_list/generic_list_get.c			\
				generic_list/generic_list_insert.c		\
				generic_list/generic_list_merge.c		\
				generic_list/generic_list_pop.c			\
				generic_list/generic_list_reverse.c		\
				generic_list/generic_list_rotate.c		\
				ptr_list/ptr_list_clear.c				\
				ptr_list/ptr_list_create.c				\
				ptr_list/ptr_list_destroy.c				\
				ptr_list/ptr_list_dup.c					\
				ptr_list/ptr_list_find.c				\
				ptr_list/ptr_list_get.c					\
				ptr_list/ptr_list_insert.c				\
				ptr_list/ptr_list_merge.c				\
				ptr_list/ptr_list_pop.c					\
				ptr_list/ptr_list_reverse.c				\
				ptr_list/ptr_list_rotate.c				\
				string_list/string_list_clear.c			\
				string_list/string_list_concat.c		\
				string_list/string_list_create.c		\
				string_list/string_list_destroy.c		\
				string_list/string_list_dup.c			\
				string_list/string_list_emplace.c		\
				string_list/string_list_find.c			\
				string_list/string_list_get.c			\
				string_list/string_list_insert.c		\
				string_list/string_list_merge.c			\
				string_list/string_list_pop.c			\
				string_list/string_list_reverse.c		\
				string_list/string_list_rotate.c		\

HEADERS		=	mylist.h								\
				mylist/